/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Adopt_animals: typeof import('./src/components/home_screens/adopt_animals.vue')['default']
    Adopt_page: typeof import('./src/components/pages/adopt_page.vue')['default']
    copy: typeof import('./src/components/home_screens/lost_animals copy.vue')['default']
    Donation_page: typeof import('./src/components/pages/donation_page.vue')['default']
    Donations: typeof import('./src/components/home_screens/donations.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/auth/login.vue')['default']
    Lost_animals: typeof import('./src/components/home_screens/lost_animals.vue')['default']
    Lost_page: typeof import('./src/components/pages/lost_page.vue')['default']
    Main_navbar: typeof import('./src/components/navbar/main_navbar.vue')['default']
    Not_found: typeof import('./src/components/not_found.vue')['default']
    Register: typeof import('./src/components/auth/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Second_navbar: typeof import('./src/components/navbar/second_navbar.vue')['default']
    Sos: typeof import('./src/components/home_screens/sos.vue')['default']
    Sos_page: typeof import('./src/components/pages/sos_page.vue')['default']
  }
}
